version: '3'

services:

  app:
    build: .
    container_name: micro-frontend-app
    entrypoint: ./.docker/entrypoint.sh
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BROWSER=none
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
    stdin_open: true
    tty: true